# CircleCI configuration file
version: 2.1

jobs:
  bobby:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "Say hello to YAML!"
  sally:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "Double trouble!"
  workflows:
    version: 2.1
    bobby_sally:
      jobs:
        - bobby
        - sally
