# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: cimg/node:18
    steps:
      - checkout
      - run: echo "testing stuff"
      - run: npm install
      - run: npm run test
  hithere:
    docker:
      - image: cimg/node:18
    steps:
      - checkout
      - run: echo "helllooooo!"
workflows:
  version: 2.1
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere
